use_frameworks!

platform :ios, '10.0'

target 'TNChart4_Example' do
  pod 'Charts', :git => 'https://github.com/Sofrano/Charts', :branch => 'Tradernet'
  pod 'TNChart4', :path => '../'
  pod 'RxCocoa', '5.1.1'
  pod 'RxSwift', '5.1.1'
  pod 'SnapKit'
  pod 'Swinject', '2.6'
  pod 'Hero'
  
end
